In [ ]:
#variable
a=1
print("its day",a)


its day 1


In [ ]:
#Arthmetic operation on two variables
a=int(input("enter a: "))
b=int(input("enter b: "))
print("sum is",a+b)
print("Difference is :",a-b)
print("product is :",a*b)
print("Quoifient is : ",a/b)
print("Remainder is :",a%b)
print("Power is :",pow(a,b))
print("Floor division :",a//b)

enter a: 200
enter b: 20
sum is 220
Difference is : 180
product is : 4000
Quoifient is :  10.0
Remainder is : 0
Power is : 10485760000000000000000000000000000000000000000
Floor division : 10


In [ ]:
#Take a salary from the user if the sal is more than 50 thusand and there is 10% tax print his final salary
a=int(input("enter the salary :"))
if a<50000:
  print("User salary is :",a)
else:
  c=a*0.10
  v=a-c
  print("salary is :",v)

enter the salary :50000
salary is : 45000.0


In [ ]:
a=int(input("Enter your salary :"))
if a<50000 :
  print("your final salary is :",a-(a*0.05))
elif a>=50000 and a<70000:
  print("your final salary is :",a-(a*0.10))
elif a>=70000 and a<100000:
  print("your final salary is :",a-(a*0.12))
else:
  print("your are promoted to next level ")

Enter your salary :100000
your are promoted to next level 


In [ ]:
a=7
b=9
print(a==b)
print(a<b)
print(a>b)
print(a<=b)
print(a>=b)

False
True
False
True
False


In [ ]:
a=6
b=9
print((a<b) and (a!=b))
print((a<b) or (a!=b))

True
True


In [ ]:
a=int(input("enter a"))
for i in range (10,0,-1):
  print(a,"X",i,"=",(a*i))

enter a11
11 X 10 = 110
11 X 9 = 99
11 X 8 = 88
11 X 7 = 77
11 X 6 = 66
11 X 5 = 55
11 X 4 = 44
11 X 3 = 33
11 X 2 = 22
11 X 1 = 11


In [ ]:
a=int(input("eneter a value"))
i=20
while (i>=10):
  print(a,"X",i,"=",(a*i))
  i=(i-1)

eneter a value999
999 X 20 = 19980
999 X 19 = 18981
999 X 18 = 17982
999 X 17 = 16983
999 X 16 = 15984
999 X 15 = 14985
999 X 14 = 13986
999 X 13 = 12987
999 X 12 = 11988
999 X 11 = 10989
999 X 10 = 9990


In [ ]:
#create a list
l1=[1,"kill",98,6.5,True]
for i in l1:
  print(i)

1
kill
98
6.5
True


In [ ]:
l1.append("boom") #listname.append(element)
print(l1)

[1, 'kill', 98, 6.5, True, 'boom']


In [ ]:
l1.insert(4,"oh") #listname.insert(index,element)
print(l1)

[1, 'kill', 98, 6.5, 'oh', True, 'boom']


In [ ]:
l2=["polo",2.4,"centerfruit","boomer",1]
l1.extend(l2) #listname>extend(another listname)
print(l1)

[1, 'kill', 98, 6.5, 'oh', True, 'boom', 'polo', 2.4, 'centerfruit', 'boomer', 1]


In [ ]:
l2.remove("polo") #listname.remove(element)
print(l2)

[2.4, 'centerfruit', 'boomer']


In [ ]:
l2.pop(1) #listname.pop(index)
print(l2)

[2.4, 'boomer']


In [ ]:
l2.clear() #listname.clear()
print(l2)

[]


In [ ]:
#create a list of 10 integer elements and print their squares
l1=[]
n=int(input("enter n"))
for i in range (1,n+1):
  l1.append(i)
l2=[i**2 for i in l1] # newlist=[outputlogic for variable in listname]
print(l2)

enter n20
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [ ]:
l1=[]
n=int(input("enter n"))
for i in range (n,n+10):
  l1.append(i)
l2=[i**2 for i in l1 if i>=50] # newlist=[outputlogic for variable in listname]
print(l2)

enter n45
[2500, 2601, 2704, 2809, 2916]


In [ ]:
l1=[23,67,12,34,69]
l2=[i*i if i>50 else "x" for i in l1]
print(l2)

['x', 4489, 'x', 'x', 4761]


In [ ]:
salary=[50000,34000,100000,0,15000]
l=[sal-(sal*0.1) if sal<=50000 else sal-(sal*0.15) for sal in salary]
print(l)

[45000.0, 30600.0, 85000.0, 0.0, 13500.0]


In [ ]:
#create a dictionary
dict1={"mentor":"ram","mentor":"krish",2:"dileep"}
print(dict1)

{'mentor': 'krish', 2: 'dileep'}


In [ ]:
dict1={"mentor":"ram","co":"krish",2:"dileep"}
print(dict1.keys())

dict_keys(['mentor', 'co', 2])


In [ ]:
dict1={"mentor":"ram","co":"krish",2:"dileep"}
print(dict1.values())

dict_values(['ram', 'krish', 'dileep'])


In [ ]:
dict1={"mentor":"ram","co":"krish",2:"dileep"}
print(dict1[2])


dileep


In [ ]:
dict1={"mentor":"ram","co":"krish",2:"dileep"}
print(dict1["mentor"])

ram


In [ ]:
dict1={9:{"mentor":"ram","co":"krish",2:"dileep"},8:{1:"kiran",3:"chaitu"},7:{4:"cse",5:"ece"}}
print(dict1[8][3])

chaitu


In [ ]:
dict1={9:{"mentor":"ram","co":"krish",2:"dileep"},8:{1:"kiran",3:"chaitu"},7:{4:"cse",5:"ece"}}
print("branch is",dict1[7][4],"name is",dict1[8][3])

branch is cse name is chaitu


In [ ]:
l1=[1,2,3,4]
l2=["kiran","chaitu","mani","tarun"]
print(dict(zip(l1,l2)))

{1: 'kiran', 2: 'chaitu', 3: 'mani', 4: 'tarun'}


In [ ]:
#NUMPY
import numpy as np
a=np.array([1,2,3,4]) #1D Array
print(a.ndim)
print(a.shape)
print(a)

1
(4,)
[1 2 3 4]


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]]) #2D Array
print(a.ndim)
print(a.shape)
print(a)

2
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],],[[13,14,15,16],[17,18,19,20],[21,2,23,24]]])
print(a.ndim)
print(a.shape)
print(a)

3
(2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21  2 23 24]]]


In [ ]:
a=np.ones((2,4,3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
a=np.zeros((2,4,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#print all  the  numbers are divisible by 8 using arange funcion.
a=np.arange(8,1001,8)
print(a)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
#splitting a range into n numbers with common differences
a=np.linspace(39,59,30)
print(a)

[39.         39.68965517 40.37931034 41.06896552 41.75862069 42.44827586
 43.13793103 43.82758621 44.51724138 45.20689655 45.89655172 46.5862069
 47.27586207 47.96551724 48.65517241 49.34482759 50.03448276 50.72413793
 51.4137931  52.10344828 52.79310345 53.48275862 54.17241379 54.86206897
 55.55172414 56.24137931 56.93103448 57.62068966 58.31034483 59.        ]


HOME WORK (TUPLES AND SETS)

In [ ]:
#tuples,collab file,documentation,qr codes task
tuple1=(10,"kiran",24.8,"joe",True)#creating a tuple
print(tuple1)

(10, 'kiran', 24.8, 'joe', True)


In [ ]:
#tuple slicing and acessing the elements from tuples
print(tuple1[0:])
print(tuple1[2])
print(tuple1[-3:-1])
print(tuple1[ ::-1])
print(tuple1[2:4])
print(tuple1[-5:-1])
print(tuple1[2:-1])

(10, 'kiran', 24.8, 'joe', True)
24.8
(24.8, 'joe')
(True, 'joe', 24.8, 'kiran', 10)
(24.8, 'joe')
(10, 'kiran', 24.8, 'joe')
(24.8, 'joe')


In [ ]:
#tuple updation
l=list(tuple1)
print(tuple1)
l[2]="orange"
tuple_updated=tuple(l)
print(tuple_updated)

(10, 'kiran', 24.8, 'joe', True)
(10, 'kiran', 'orange', 'joe', True)


In [ ]:
#tuple deletion
list1=list(tuple1)
print(tuple1)
list1.pop()
list1.pop(0)
list1.remove("joe")
tuple_updated=tuple(list1)
print(tuple_updated)


(10, 'kiran', 24.8, 'joe', True)
('kiran', 24.8)


In [ ]:
#clear the tuple
list1=list(tuple1)
print(tuple1)
list1.clear()
tuple_updated=tuple(list1)
print(tuple_updated)

(10, 'kiran', 24.8, 'joe', True)
()


In [ ]:
#inserting the element
list1=list(tuple1)
print(tuple1)
list1.insert(4,"orange")
list1.append(5)
tuple_updated=tuple(list1)
print(tuple_updated)

(10, 'kiran', 24.8, 'joe', True)
(10, 'kiran', 24.8, 'joe', 'orange', True, 5)


In [ ]:
#tuple operations
tuple1=(1,8,5,3,88,32,5)
print(tuple1.count("88"))
print(tuple1.index(1))
print(len(tuple1))
print("sorted tuple is",sorted(tuple1))
tuple2=(tuple1)*3
print(tuple2)

0
0
7
sorted tuple is [1, 3, 5, 5, 8, 32, 88]
(1, 8, 5, 3, 88, 32, 5, 1, 8, 5, 3, 88, 32, 5, 1, 8, 5, 3, 88, 32, 5)


In [ ]:
#dictionary using two tuple
tuple1=(1,8.9,"kiran","chaitu",True)
tuple2=("rno","percent","student1","student2","verification")
print(dict(zip(tuple2,tuple1)))

{'rno': 1, 'percent': 8.9, 'student1': 'kiran', 'student2': 'chaitu', 'verification': True}


In [ ]:
# Program to perform different set operations
A = {0, 2, 4, 6, 8};
B = {1, 2, 3, 4, 5};

# union
print("Union :", A.union(B))

# intersection
print("Intersection :", A.intersection(B))

# difference
print("Difference :", A.difference(B))

# symmetric difference
print("Symmetric difference :", A.symmetric_difference(B))

#subset or not
print(A.issubset(B))


Union : {0, 1, 2, 3, 4, 5, 6, 8}
Intersection : {2, 4}
Difference : {0, 8, 6}
Symmetric difference : {0, 1, 3, 5, 6, 8}
False


In [ ]:
# create a set of integer type
student_id = {112, 114, 116, 118, 115}
print('Student ID:', student_id)

# create a set of string type
vowel_letters = {'a', 'e', 'i', 'o', 'u'}
print('Vowel Letters:', vowel_letters)

# create a set of different data types
mixed = {'Hello', 101, -2, 'Bye'}
print('Set of mixed data types:', mixed)

Student ID: {112, 114, 115, 116, 118}
Vowel Letters: {'i', 'a', 'u', 'o', 'e'}
Set of mixed data types: {'Bye', 'Hello', 101, -2}


In [ ]:
set1 = {"apple", "banana", "cherry", "apple"}#set with duplicate elements
print(set1)

{'apple', 'cherry', 'banana'}
