In [ ]:
import numpy as np
a=np.arange(1,13).reshape(3,4)
print((a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
b=np.linspace(1,13,12).reshape(3,4)
print(b)

[[ 1.          2.09090909  3.18181818  4.27272727]
 [ 5.36363636  6.45454545  7.54545455  8.63636364]
 [ 9.72727273 10.81818182 11.90909091 13.        ]]


In [ ]:
b=np.array([21,46,78,94,25,57,45,98]).reshape(2,2,2)# channges the shape of array
print(b)

[[[21 46]
  [78 94]]

 [[25 57]
  [45 98]]]


In [ ]:
#change the size of array
(b.resize(2,2,2))
print(b)

[[[21 46]
  [78 94]]

 [[25 57]
  [45 98]]]


ARRAY OPERATIONS

In [ ]:
a=np.array([23,47,35,52,98,96])
b=np.array([43,35,33,67,23,28])
print(a-b)
print(a+b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a==b)
print(a>=b)

[-20  12   2 -15  75  68]
[ 66  82  68 119 121 124]
[ 989 1645 1155 3484 2254 2688]
[0.53488372 1.34285714 1.06060606 0.7761194  4.26086957 3.42857143]
[0 1 1 0 4 3]
[23 12  2 52  6 12]
[False False False False False False]
[False  True  True False  True  True]


In [ ]:
b=np.array([21,46,78,94]).reshape(2,2)
print("matrix a is:")
print(a)
a=np.arange(1,5).reshape(2,2)
print("matrix b is :")
print(b)
print("product of two matrixes is")
print(a*b)# elements multiplication


matrix a is:
[[1 2]
 [3 4]]
matrix b is :
[[21 46]
 [78 94]]
product of two matrixes is
[[ 21  92]
 [234 376]]


In [ ]:
b=np.array([21,46,78,94]).reshape(2,2)
print("matrix a is:")
print(a)
a=np.arange(1,5).reshape(2,2)
print("matrix b is :")
print(b)
print("product of two matrixes is")
print(a@b)#matrix multplication


matrix a is:
[[1 2]
 [3 4]]
matrix b is :
[[21 46]
 [78 94]]
product of two matrixes is
[[177 234]
 [375 514]]


In [ ]:
b=np.array([21,46,78,94]).reshape(2,2)
print("matrix a is:")
print(a)
a=np.arange(1,5).reshape(2,2)
print("matrix b is :")
print(b)
print("product of two matrixes is")
print(a.dot(b))# matrix multiplication


matrix a is:
[[1 2]
 [3 4]]
matrix b is :
[[21 46]
 [78 94]]
product of two matrixes is
[[177 234]
 [375 514]]


In [ ]:
b=np.array([21,46,78,94]).reshape(2,2)
print("max of b:",b.max())# max of array
print("min of b:",b.min())# min of array


max of b: 94
min of b: 21


In [ ]:
b=np.array([21,46,78,94]).reshape(2,2)
print("matrix b is:")
print(b)
print("cloumn  max elements is:")
print(b.max(axis=0)) #max element in every coloumn
print("row  max elements is:")
print(b.max(axis=1)) #max element in every row
print("cloumn  min elements is:")
print(b.min(axis=0)) # min element in every coloumn
print("row  min elements is:")
print(b.min(axis=1)) # min element in every row

matrix a is:
[[21 46]
 [78 94]]
cloumn  max elements is:
[78 94]
row  max elements is:
[46 94]
cloumn  min elements is:
[21 46]
row  min elements is:
[21 78]


In [ ]:
# Joining Arrays or Stacking Arrays
b=np.array([21,46,78,94]).reshape(2,2)
print("matrix b is :")
print(b)
a=np.arange(1,5).reshape(2,2)
print("matrix a is :")
print(a)
print("after  vertically stacking arrays : ")
print(np.vstack((a,b))) # vertical stacking arrays
print("after  horizantal stacking arrays :")
print(np.hstack((a,b))) # horizantal stacking arrays
print("after  axis=0 stacking arrays :")
print(np.stack((a,b),axis=0)) # axis=0 stacking arrays
print("after  axis=1 stacking arrays :")
print(np.stack((a,b),axis=1)) # axis=1 stacking arrays
print("after  dstacking arrays :")
print(np.dstack((a,b))) # dimensional stack rows->columns and columns->rows



matrix b is :
[[21 46]
 [78 94]]
matrix a is :
[[1 2]
 [3 4]]
after  vertically stacking arrays : 
[[ 1  2]
 [ 3  4]
 [21 46]
 [78 94]]
after  horizantal stacking arrays :
[[ 1  2 21 46]
 [ 3  4 78 94]]
after  axis=0 stacking arrays :
[[[ 1  2]
  [ 3  4]]

 [[21 46]
  [78 94]]]
after  axis=1 stacking arrays :
[[[ 1  2]
  [21 46]]

 [[ 3  4]
  [78 94]]]
after  dstacking arrays :
[[[ 1 21]
  [ 2 46]]

 [[ 3 78]
  [ 4 94]]]


In [ ]:
#splitting arrays
b=np.array([21,46,78,94]).reshape(2,2)
print("matrix b is :")
print(b)
print("after splitting vertically :")
print(np.vsplit(a,2))
print("after splitting horizantally :")
np.hsplit(a,2)


matrix b is :
[[21 46]
 [78 94]]
after splitting vertically :
[array([[1, 2]]), array([[3, 4]])]
after splitting horizantally :


[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [ ]:
b=np.arange(18).reshape(6,3)
print("matrix b is :")
print(b)
print("after splitting vertically :")
print((np.vsplit(a,(3,2))))
print("after splitting horizantally :")
(np.hsplit(a,(2,5)))

matrix b is :
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after splitting vertically :
[array([[1, 2],
       [3, 4]]), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64)]
after splitting horizantally :


[array([[1, 2],
        [3, 4]]),
 array([], shape=(2, 0), dtype=int64),
 array([], shape=(2, 0), dtype=int64)]

In [ ]:
b=np.arange(18).reshape(6,3)
print("matrix b is :")
print(b)
print("after argmax  :")
print((b.argmax(axis=0)))

matrix b is :
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after argmax  :
[5 5 5]


In [ ]:
b=np.arange(18).reshape(6,3)
print("matrix b is :")
print(b)
print("after argmax  :")
print((b.argmax(axis=1)))

matrix b is :
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after argmax  :
[2 2 2 2 2 2]


In [ ]:
b=np.arange(18).reshape(6,3)
print("matrix b is :")
print(b)
print("after argmin  :")
print((b.argmin(axis=0)))

matrix b is :
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after argmin  :
[0 0 0]


In [ ]:
b=np.arange(18).reshape(6,3)
print("matrix b is :")
print(b)
print("after argmin  :")
print((b.argmin(axis=1)))

matrix b is :
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after argmin  :
[0 0 0 0 0 0]


In [ ]:
b=np.arange(18).reshape(6,3)
print("mean is :",np.mean(b))
print("median :",np.median(b))
print("varience :",np.var(b))
print("standard deviation :",np.std(b))

mean is : 8.5
median : 8.5
varience : 26.916666666666668
standard deviation : 5.188127472091127


In [ ]:
a=np.pi
a

3.141592653589793

In [ ]:
np.rad2deg(a)

180.0

In [ ]:
c=np.array([0,30,45,60,90,120,180])
np.deg2rad(c)

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       2.0943951 , 3.14159265])

In [ ]:
np.sin(c)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(c)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(c)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(c)

<ipython-input-90-6473c7b6e743>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(c)


array([ 0., nan, nan, nan, nan, nan, nan])

In [ ]:
np.arccos(c)

<ipython-input-91-387b33b2cf93>:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(c)


array([1.57079633,        nan,        nan,        nan,        nan,
              nan,        nan])

In [ ]:
np.arctan(c)

array([0.        , 1.53747533, 1.54857776, 1.5541312 , 1.55968567,
       1.56246319, 1.56524083])

In [ ]:
#search of array
import numpy as np
a=np.array([45,67,23,97,38])
print(np.where(a%2==0))
print(np.where(a==97))

(array([4]),)
(array([3]),)


In [ ]:
a=np.array([8,9,67,89,93])
print(np.searchsorted(a,56))

2


In [ ]:
import numpy as np
a=np.array([22,34.47,56.11,78,32])
b=np.array([3,23,67,22,27])
#arthimetic operations
print(np.sort(a))
print(np.sort(b))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(divmod(a,b))
print(np.diff(a))
print(np.diff(b))
#set opreations
print(np.intersect1d(a,b))
print(np.union1d(a,b))
print(np.setdiff1d(a,b))
#rounding
print(np.trunc(a))
print(np.fix(a))
print(np.around(a,1))
print(np.floor(a))
print(np.ceil(a))
#cummulative opeartions
print(np.cumsum(a))
print(np.cumprod(a))

[22.   32.   34.47 56.11 78.  ]
[ 3 22 23 27 67]
[ 25.    57.47 123.11 100.    59.  ]
[ 19.    11.47 -10.89  56.     5.  ]
[  66.    792.81 3759.37 1716.    864.  ]
[7.33333333 1.49869565 0.83746269 3.54545455 1.18518519]
[ 1.   11.47 56.11 12.    5.  ]
(array([7., 1., 0., 3., 1.]), array([ 1.  , 11.47, 56.11, 12.  ,  5.  ]))
[ 12.47  21.64  21.89 -46.  ]
[ 20  44 -45   5]
[22.]
[ 3.   22.   23.   27.   32.   34.47 56.11 67.   78.  ]
[32.   34.47 56.11 78.  ]
[22. 34. 56. 78. 32.]
[22. 34. 56. 78. 32.]
[22.  34.5 56.1 78.  32. ]
[22. 34. 56. 78. 32.]
[22. 35. 57. 78. 32.]
[ 22.    56.47 112.58 190.58 222.58]
[2.20000000e+01 7.58340000e+02 4.25504574e+04 3.31893568e+06
 1.06205942e+08]


In [ ]:
#lcm and gcd
ar=np.array([12,35,23,67,3245])
print(np.lcm.reduce(ar))
print(np.gcd.reduce(ar))

420045780
1


In [ ]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a)) # it gives inverse of matrix 'a'

[[-2.   1. ]
 [ 1.5 -0.5]]


In [3]:
import random as rd
A= rd.random() # default limit 0 to 99   #rand(n)
print(A)
A= rd.randint(1,4)
print(A)
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.outer(a,b))    #
#joins
a=np.array([1,2,3])
b=np.array([4,5,6])
#1*4 + 2*5 + 3*6 =32
print(np.inner(a,b))

0.9431117257188981
2
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
32
