In [ ]:
import numpy as np

In [ ]:
#reshape-changes made are need to be saved in another variable
A=np.arange(1,13).reshape(3,4)
print(A)


[4.         3.90909091 3.81818182 3.72727273 3.63636364 3.54545455
 3.45454545 3.36363636 3.27272727 3.18181818 3.09090909 3.        ]


In [ ]:

A=np.linspace(4,8,12).reshape(3,4)
print(A)


[[4.         4.36363636 4.72727273 5.09090909]
 [5.45454545 5.81818182 6.18181818 6.54545455]
 [6.90909091 7.27272727 7.63636364 8.        ]]


In [ ]:
B=np.array([12,56,89,56,14,6,78,90,]).reshape(2,2,2)
print(B)

[[[12 56]
  [89 56]]

 [[14  6]
  [78 90]]]


In [ ]:
#resize
B=np.array([12,56,89,56,14,6,78,90,])
B.resize(2,2,2)#changes the shape of original array
print(B)

[[[12 56]
  [89 56]]

 [[14  6]
  [78 90]]]


In [ ]:
#to find the max and min element of the array
A=np.array([12,90,78,4])
print(A.min())
print(A.max())

4
90


In [ ]:
#array operations
A=np.array([12,56,78,3])
B=np.array([90,45,78,1])
C=A-B        #a list will throw an error while array iterates themselves
print(C)
print(A-B)

[-78  11   0   2]
[-78  11   0   2]


In [ ]:
#array operations
A=np.array([12,56,78,3])
B=np.array([90,45,78,1])
C=A+B        #a list will throw an error while array iterates themselves
print(C)
print(A+B)

[102 101 156   4]
[102 101 156   4]


In [ ]:
#one on one multiplication
A=np.array([45,67,21,8]).reshape(2,2)
B=np.array([34,67,2,7]).reshape(2,2)
print(A)
print("---------------------------")
print(B)
print("---------------------------")
C=A*B
print(C)

[[45 67]
 [21  8]]
---------------------------
[[34 67]
 [ 2  7]]
---------------------------
[[1530 4489]
 [  42   56]]


In [ ]:
#matrix multiplication
A=np.array([45,67,21,8]).reshape(2,2)
B=np.array([34,67,2,7]).reshape(2,2)
print(A)
print("---------------------------")
print(B)
print("---------------------------")
C=A@B
print(C)

[[45 67]
 [21  8]]
---------------------------
[[34 67]
 [ 2  7]]
---------------------------
[[1664 3484]
 [ 730 1463]]


In [ ]:
#matrix multiplication
A=np.array([45,67,21,8]).reshape(2,2)
B=np.array([34,67,2,7]).reshape(2,2)
print(A)
print("---------------------------")
print(B)
print("---------------------------")
C=A .dot(B)
print(C)

[[45 67]
 [21  8]]
---------------------------
[[34 67]
 [ 2  7]]
---------------------------
[[1664 3484]
 [ 730 1463]]


In [ ]:
#max elements ammong each row and column
A=np.array([45,67,21,8,8,90,78,45]).reshape(4,2)
print(A)
print("-----------------------")
print(A.max(axis=0))           #axis=0 -column
print("-----------------------")
print(A.max(axis=1))           #axis=1 -row


[[45 67]
 [21  8]
 [ 8 90]
 [78 45]]
-----------------------
[78 90]
-----------------------
[67 21 90 78]


In [ ]:
#min elements among each row and column
A=np.array([45,67,21,8,8,90,78,45]).reshape(4,2)
print(A)
print("-----------------------")
print(A.min(axis=0))           #axis=0 -column
print("-----------------------")
print(A.min(axis=1))           #axis=1 -row


[[45 67]
 [21  8]
 [ 8 90]
 [78 45]]
-----------------------
[8 8]
-----------------------
[45  8  8 45]


In [ ]:
# joining arrays vertically
A=np.array([45,67,21,8]).reshape(2,2)
B=np.array([34,67,2,7]).reshape(2,2)
print(A)
print("---------------------------")
print(B)
print("---------------------------")
print("After vertically stacking the arrays")
print(np.vstack((A,B)))


[[45 67]
 [21  8]]
---------------------------
[[34 67]
 [ 2  7]]
---------------------------
After vertically stacking the arrays
[[45 67]
 [21  8]
 [34 67]
 [ 2  7]]


In [ ]:
# joining arrays horizontally
A=np.array([45,67,21,8]).reshape(2,2)
B=np.array([34,67,2,7]).reshape(2,2)
print(A)
print("---------------------------")
print(B)
print("---------------------------")
print("After horizontally stacking the arrays")
print(np.hstack((A,B)))

[[45 67]
 [21  8]]
---------------------------
[[34 67]
 [ 2  7]]
---------------------------
After horizontally stacking the arrays
[[45 67 34 67]
 [21  8  2  7]]


In [ ]:
# joining arrays
A=np.array([45,67,21,8]).reshape(2,2)
B=np.array([34,67,2,7]).reshape(2,2)
print(A)
print("---------------------------")
print(B)
print("---------------------------")
print("After  stacking the arrays")
print(np.stack((A,B),axis=0))

[[45 67]
 [21  8]]
---------------------------
[[34 67]
 [ 2  7]]
---------------------------
After  stacking the arrays
[[[45 67]
  [21  8]]

 [[34 67]
  [ 2  7]]]


In [ ]:
# joining arrays
A=np.array([45,67,21,8]).reshape(2,2)
B=np.array([34,67,2,7]).reshape(2,2)
print(A)
print("---------------------------")
print(B)
print("---------------------------")
print("After  stacking the arrays")
print(np.stack((A,B),axis=1))

[[45 67]
 [21  8]]
---------------------------
[[34 67]
 [ 2  7]]
---------------------------
After  stacking the arrays
[[[45 67]
  [34 67]]

 [[21  8]
  [ 2  7]]]


In [ ]:
#dimentionality stack
A=np.arange(30).reshape(2,3,5)
print(A)
print("After dstack")
print(np.dstack(A))#no.of rows -->no.of groups
#no.of columns in every group -->no.of rows in every group
#            g   r  c
#original   2    3  5
#changed    5   2   3
#changed    c   g   r

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays vertically
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting the array to required no of parts vertically
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

[[ 0  1  2]#1
 [ 3  4  5]#2
 [ 6  7  8]#3
 [ 9 10 11]#4
 [12 13 14]#5
 [15 16 17]]#6
After splitting
[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]
[ ]


In [ ]:
#splitting arrays horizontally
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.hsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
#splitting the array to required no of parts horizontally
A=np.arange(18).reshape(3,6)
print(A)
print("After splitting")
np.hsplit(A,(2,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [ ]:
A=np.array([12,89,78,67,96,7,9,8,1,3]).reshape(5,2)
print(A)
print(A.argmax())#returns the position of the max element in the array

[[12 89]
 [78 67]
 [96  7]
 [ 9  8]
 [ 1  3]]
4


In [ ]:
A=np.array([12,89,78,67,96,7,9,8,1,3]).reshape(5,2)
print(A)
print(A.argmax(axis=0))      #columns                   #rows
                          #   0  0  0              0   1    2
                          #   1  1  1              0   1    2
                          #   2  2  2              0   1   2
print(A.argmax(axis=1))


[[12 89]
 [78 67]
 [96  7]
 [ 9  8]
 [ 1  3]]
[2 0]
[1 0 0 0 1]


In [ ]:
A=np.array([12,89,78,67,96,7,9,8,1,3]).reshape(5,2)
print(A)
print(A.argmin())#returns the position of the min element in the array


[[12 89]
 [78 67]
 [96  7]
 [ 9  8]
 [ 1  3]]
8


In [ ]:
#MEAN,MEDIAN,STD,VAR
A=np.array([12,34,26,66,71,88])
print("Mean:",np.mean(A))
print("Median:",np.median(A))
print("variance:",np.var(A))

Mean: 49.5
Median: 50.0
variance: 735.9166666666666


In [ ]:
#trigonometry
A=np.pi
print(A)


3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
C=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi/1])
print(C)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
B=np.array([ 0,30,45,60,90,120,180])
D=np.deg2rad(B)
print(D)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(B)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(B)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(B)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arctan(B) #tan^-1

array([0.        , 1.53747533, 1.54857776, 1.5541312 , 1.55968567,
       1.56246319, 1.56524083])

In [ ]:
np.arcsin(1)#sin^1

1.5707963267948966

In [ ]:
np.arccos(1)

0.0

In [ ]:
#calculating hypotenuse
a=8
b=6
print(np.hypot(a,b))

10.0


In [ ]:
#searching
A=np.array([90,3,5,21,34,90,21])#greater than 25
print(np.where(A>25))

(array([0, 4, 5]),)


In [ ]:
#searching
A=np.array([90,3,5,21,34,90,21])#even
print(np.where(A%2==0))

(array([0, 4, 5]),)


In [ ]:
A=np.array([12,2,4,89,7,9])  #2 4 7 9 12 89
print(np.searchsorted(A,7))  #output the index of the search element after sorting the list


3


In [ ]:
#linear algebra
A=np.array([6,56,78,90])
B=np.array([64,5,8,9])
print(np.add(A,B))  #adding two arrays
print(np.subtract(A,B))  #subtracting 2 arrays

[70 61 86 99]
[-58  51  70  81]


In [ ]:
print(np.divide(A,B))    #quotient

[ 0.09375 11.2      9.75    10.     ]


In [ ]:
print(np.divmod(A,B))    #quotient and remainder

(array([ 0, 11,  9, 10]), array([6, 1, 6, 0]))


In [ ]:
A=np.array([6,56,78,90])
print(np.diff(A))

[50 22 12]


In [ ]:
#sort
A=np.array([6,56,78,90])
print(np.sort(A))

[ 6 56 78 90]


In [ ]:
#set functions
#union
A=np.array([6,56,78,90])
B=np.array([64,5,8,9])
print(np.union1d(A,B))

[ 5  6  8  9 56 64 78 90]


In [ ]:
A=np.array([6,56,78,90])
B=np.array([64,90,5,8,9])
print(np.intersect1d(A,B))

[90]


In [ ]:
A=np.array([6,56,78,90])
B=np.array([64,90,5,8,9])
print(np.setdiff1d(A,B))

[ 6 56 78]


In [ ]:
#rounding trunc
A=np.array([6.00007,5.896,7.098,998.0])
print(np.trunc(A))

[  6.   5.   7. 998.]


In [ ]:
#fix
A=np.array([6.00007,5.896,7.098,998.0])
print(np.fix(A))


[  6.   5.   7. 998.]


In [ ]:
#floor
A=np.array([6.00007,5.896,7.098,998.0])
print(np.floor(A))

[  6.   5.   7. 998.]


In [ ]:
#ceil
A=np.array([6.00007,5.896,7.098,998.0])
print(np.ceil(A))

[  7.   6.   8. 998.]


In [ ]:
#around
A=np.array([6.00007,5.896,7.098,998.0])
print(np.around(A))

[  6.   6.   7. 998.]


In [ ]:
#cumulative sum
A=np.array([600007,5896,7098,9980])
print(np.cumsum(A))

[600007 605903 613001 622981]


In [ ]:
#cumulative product
A=np.array([600007,5896,7098,9980])
print(np.cumprod(A))

[            600007         3537641272     25110177748656
 250599573931586880]


In [ ]:
#lcm and gcd
print(np.lcm(47,8))
print(np.gcd(47,8))

376
1


In [ ]:
#to find lcm and gcd for array
A=np.array([6,56,78,90])
print(np.lcm.reduce(A))
print(np.gcd.reduce(A))

32760
2


In [ ]:
#finding the inverse matrix
A=np.array([[1,2],[3,4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#importing random
from numpy import random as rd

In [ ]:
#generating a random number
A=rd.rand()# limit is 0 to 0.99
print(A)

0.8170466846365986


In [ ]:
A=rd.randint(5)#randint(limit) -->limit=0,1,2,3,4
print(A)

2


In [ ]:
A=rd.rand(10)#       rd.rand(n)  displays random "n" numbers with range 0 to 0.99
print(A)

[0.81188119 0.48397303 0.08986563 0.55920203 0.47126665 0.61454245
 0.33526006 0.65970211 0.17438335 0.19138727]


In [ ]:
A=rd.randint(50,size=6)#prints the random numbers upto limit in given size
print(A)

[44 36 36 11 15 29]


In [ ]:
A=rd.randint(50,size=(2,3))#limit with shape
print(A)

[[48 22 35]
 [10 15 13]]


In [ ]:
A=np.array([6,56,78,90])
B=np.array([64,90,5,8])
#6*64 +56*90 + 78*5 +90*8
print(np.inner(A,B))

6534


In [ ]:
A=np.array([6,56,78,90])
B=np.array([64,90,5,8])
#6*64+56*90 +78*5+90*8
print(np.outer(A,B))

[[ 384  540   30   48]
 [3584 5040  280  448]
 [4992 7020  390  624]
 [5760 8100  450  720]]


In [ ]:
#cross product
A=np.array([6,56,78])
B=np.array([64,90,5])
print(np.cross(A,B))

[-6740  4962 -3044]
